### ISSUE TITLE
ID birthdate question: 
User feedback: something
(`children[0].birthdate`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#13]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `birthdate question`
Details | Would it be possible to collect date in a single field so people can use the calendar selector? (open to being persuaded against it if you have thoughts, but my initial instinct is it's nicer in one field)
Variable being sought | `children[0].birthdate`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
How it works in Letter to landlord interview:
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/07828007-c7d6-4970-a561-f828b0a179d1)
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/4347767f-d414-4a00-9803-4377054c5a3f)

**Comment by h-mcguire** [comment]
Definitely possible! Changed it over to the the date datatype. I also moved it onto the same screen the name gets gathered. I think this will work better when dealing with cases involving a bunch of kids.
