### ISSUE TITLE
form output feedback

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#15]
Great job guys!  A few things I noticed on the forms:

For Paragraph 4 it says NA, but should say see attached or something like that.
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/21128a76-b7ee-4017-9020-5955d858d7f9)

Party phone numbers appear on output from old tool, but not here on new tool:
<img width="422" alt="image" src="https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/a456f8cd-8117-4910-afbe-6fb595392f88">

Judicial circuit missing (probably that's what you were asking about when you mentioned the "division" in your email?):
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/5e5ebdb3-41c8-4515-9993-d477bbf4c288)

On addendum first reference to children only includes the first child (I entered 3):
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/2c54f290-23cd-4ebb-b08d-dc711cf05407)
And reference here is to singular child instead of children:
<img width="456" alt="image" src="https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/58355347-d4b3-42d7-8054-c39a2e43ab97">

Second reference to children does name all three but only includes space for one DOB and does not list the DOBs at all.
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/1f0bd358-5cb6-4985-bc29-6865743c3491)

**Comment by ekressmiller** [comment]
For order regarding change of domicile, party phone numbers and court circuit number are also missing.

For order re parenting time, the above is true, plus case number is missing (case number should probably appear on both pages of this order)

**Comment by h-mcguire** [comment]
All resolved on addendum branch. The commits were c382e45 and 63a5b70.
