### ISSUE TITLE
populating court info

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#17]
@RamiLorca @h-mcguire 

So, to populate the court info, I _think_ something like this should work. 

The framework has the underlying module and spreadsheet source document for populating court information.

In some cases, we need the person to pick their county and then also pick their court. But here I think they can just pick county because all family law cases are circuit court cases, and there's only one circuit court per county.  I'm mostly basing this on what Bryce did in the child support interview, because the same is true there.

So first in the interview order, you need to call these:

  county_choice
  court_index
  the_court

county_choice is the question asking county.
court_index is getting them to pick the specific court (but here we do that by code because we already know based on county)
and the_court loads the necessary information into the AL_court_loader object

You need a code block to tell court_index which court to choose:
code: |
  court_index = next(court_list.filter_courts_by_2([county_choice], ['circuit'], column_1='address_county', column_2='type'))[0]

Then in the attachment block you fill in the information with the_court.whatever_attribute_you_want_from_the_spreadsheet_in_the_framework

e.g.:

    - trial_court_address_on_one_line: ${ the_court.address.on_one_line() }
    - trial_court_phone_number: ${ the_court.phone }

for the circuit number it should be the_court.number

Let me know if that helps!

**Comment by normon66** [comment]
Additionally, I added a couple code blocks to the [framework](https://github.com/mplp/docassemble-mlhframework/blob/bh_framework_dev/docassemble/mlhframework/data/questions/mlh_interview_framework.yml) on the [bh_framework_dev](https://github.com/mplp/docassemble-mlhframework/tree/bh_framework_dev) branch for use in collecting court information.

`court_type_selection`: This will allow the user to select the type of court that their case is in (Circuit, District, or Probate). [See code here](https://github.com/mplp/docassemble-mlhframework/blob/327206483f2fdb5ad89ae5b743b45750289fb2d0/docassemble/mlhframework/data/questions/mlh_interview_framework.yml#L478).

`court_count`: Can be used to determine how many courts of a certain type there are in a certain county. [See code here](court_count).

`court_index_for_specific_court_type`: Once a user selects their court type and county, this will allow the user to select which of those courts the case is in, if there are multiple. For example, there are 17 or so unique District Courts in Wayne County. [See code here](https://github.com/mplp/docassemble-mlhframework/blob/327206483f2fdb5ad89ae5b743b45750289fb2d0/docassemble/mlhframework/data/questions/mlh_interview_framework.yml#L515).
