### ISSUE TITLE
Minor: suggest use of framework variable

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#21]
Can utilize `${ MLH_GUIDE_FULL }` instead of writing out the entire phrase and link.

https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/blob/4a7ee75a36e70abc3894bb7ff72fab63147a6643/docassemble/MLHMotionRegardingChangeOfDomicile/data/questions/motion_regarding_change_of_domicile.yml#L371

https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/blob/4a7ee75a36e70abc3894bb7ff72fab63147a6643/docassemble/MLHMotionRegardingChangeOfDomicile/data/questions/motion_regarding_change_of_domicile.yml#L520

**Comment by h-mcguire** [comment]
Resolved in PR #36
