### ISSUE TITLE
ID judgment or custody order: 
User feedback: bug
(`prior_order_yesno`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#22]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `judgment or custody order`
Details | On the page with id 'judgment or custody order', I get the below error if I select No and then Continue.

name 'current_custody' is not defined
Variable being sought | `prior_order_yesno`
Package version | `playground`
Filename | `docassemble.playground5MotionChangeDomicile:motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Resolved in PR #18 
Same bug as issue #6
