### ISSUE TITLE
Form issue: E(4) should show "See attached"

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#25]
Using the attached json answer set, paragraph 4 is shown in its entirety on the attachment to the motion, but the motion itself shows "N/A under paragraph 4 instead of "See attachment"

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/32527754/a863a763-0e0e-4f86-aebb-43e25910a622)

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/32527754/074a7f3b-a893-402a-9adf-507b06f412f9)

[variables.json](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/files/14513669/variables.json)

**Comment by h-mcguire** [comment]
I changed the attachment block so it always displays "See attached."  I'm under the impression there's no situations when it should be "N/A." Update is in commit [6ccdda0](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/commit/6ccdda01387def3d9ec0a195711fa5a0aa887aec)
