### ISSUE TITLE
Minor: County formatting in captions

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#27]
In all forms, county should be right-aligned and CAPS and with font sizing consistent to static text.

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/32527754/ec9d268a-331c-41cf-8a5a-0f02ef00e31e)

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/32527754/c92b501d-aec2-408e-a95d-6b2acb2f8582)

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/32527754/e8b8d251-a341-46f0-98c2-727374c681b3)

**Comment by RamiLorca** [comment]
Issued resolved in latest main branch merge.
