### ISSUE TITLE
Gather supporting documents for DV cases

### ISSUE THREAD

**Issue by h-mcguire** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#34]
The LHI interview tells the user they can submit additional documents to support a DV showing (e.g. police records). I don't think the LHI interview gathered these documents, do we know if this was a choice or a technical limitation?

I was thinking we should add a screen to gather those documents and bundle them with PDF for the motion. Making this issue to flag the idea for folks.

**Comment by RamiLorca** [comment]
Closing issue since we'll be moving ahead with document gathering feature.
