### ISSUE TITLE
ID what_you_will_need: 
User feedback: something
(`what_you_will_need`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#46]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `what_you_will_need`
Details | I would suggest condensing the first two screens into one. I would basically have something that looks like the first screen, but delete the final paragraph and add a new paragraph with: "If you need more help, you can use the Guide to Legal Help to search for a lawyer or legal services." 

Then I would also suggest moving the "When do you need court permission?" screen up to the 2nd screen to better match where that info shows up in the LHI version.
Variable being sought | `what_you_will_need`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
I shifted it to the second screen and tried to get the formatting of the text to look right. Update in commit 77d0004.
