### ISSUE TITLE
ID what_you_will_need: 
User feedback: something
(`what_you_will_need`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#47]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `what_you_will_need`
Details | Seeing this makes me want to add an optional section for "what you will need" to the framework question MLH_intro_time so we can condense this and have fewer intro screens. 

So no action required right now. If/when I do that I will follow up with a comment here.
Variable being sought | `what_you_will_need`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by RamiLorca** [comment]
@MPLP-Docassemble Following up on this issue. Any updates?

**Comment by ekressmiller** [comment]
MLH_intro_landing in the framework now includes places for both the time estimate and the materials needed, so it could be condensed if that made sense with how the intro screens are currently working for this interview. 

I can pay particular attention to the intro screens when I do my next dev test and suggest condensing if I still think it makes sense.
