### ISSUE TITLE
ID what is the user's role?: 
User feedback: something
(`user_started_case`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#48]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `what is the user's role?`
Details | I think it'd be good to also include Bryce's help text from the child support interview here. I will move the help template to the framework and then comment here to let you know it can be added to your interview.
Variable being sought | `user_started_case`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by RamiLorca** [comment]
@MPLP-Docassemble Following up on this issue. Any updates on the help text?

**Comment by ekressmiller** [comment]
Yes, it's in the framework now! It would be a collapsible template using this template: help_user_ask_role_template
