### ISSUE TITLE
ID judgment or custody order: 
User feedback: something
(`prior_order_yesno`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#49]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `judgment or custody order`
Details | same "no label" issue here. I'm making a note to ask about this at the next Suffolk meeting and we can discuss at our next dev meeting as well, so feel free to hold off until then.
Variable being sought | `prior_order_yesno`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Updated! I added labels to replace any use of no label in commit a4c21ce.
