### ISSUE TITLE
ID moving benefits explanation: 
User feedback: something
(`moving_benefits`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#50]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `moving benefits explanation`
Details | please make "Please complete the following: The move will improve the quality of life for my child and me because…" the label instead of part of the subquestion.
Variable being sought | `moving_benefits`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Changes in commit 7580c30
