### ISSUE TITLE
ID moving reason explanation: 
User feedback: language
(`moving_reason`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#51]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `moving reason explanation`
Details | Please make "Please use complete sentences to explain why you want to move." the label instead of part of the subquestion
Variable being sought | `moving_reason`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Updated in commit bd84d56
