### ISSUE TITLE
ID wants parenting time change: 
User feedback: something
(`wants_parenting_time_change`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#53]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `wants parenting time change`
Details | I think it would be good to change the longer labels here to "label above field = True" to make them more readable. https://docassemble.org/docs/fields.html#label%20above%20field
Variable being sought | `wants_parenting_time_change`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Updated in commit c2f89af
