### ISSUE TITLE
ID wants parenting time change: 
User feedback: something
(`wants_parenting_time_change`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#54]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `wants parenting time change`
Details | I think it would be good to reduce the number of sections.  I would suggest: remove "Do You Qualify? and include those questions under "Prior Case Information"; cut "Domestic Violence" and include those questions under "Why You Want to Move"; cut "Electronic Signature" and include that under "Download Your Forms"
Variable being sought | `wants_parenting_time_change`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Done! Updated in commit f7011f0 

We might be able to also condense "Your New Address" and "Parenting Time" into a single section called something like "Desired Changes to Order"
