### ISSUE TITLE
ID DownloadScreen: 
User feedback: language
(`motion_re_change_of_domicile_download`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#55]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `DownloadScreen`
Details | For accessible_instructions_link can you please use: https://michiganlegalhelp.org/step/3950 (this is a direct link to just the instructions, so it's the most analogous to the paper instructions)
For resource_page_link can you please use: https://michiganlegalhelp.org/node/3949 (this is just a shorter version of the link you originally had for accessible_instructions_link  -I'm trying to use this shorter version because I'm thinking about a situation where someone printed these forms and needs to type the address in to get to the instructions)
Variable being sought | `motion_re_change_of_domicile_download`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Updated in commit 430161a
