### ISSUE TITLE
ID DownloadScreen: 
User feedback: something
(`motion_re_change_of_domicile_download`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#56]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `DownloadScreen`
Details | We want the coversheet and instructions to come out as a single document, then all other individual forms should come out separately (but with any addenda included in same doc with the form they go with).  

I think we also want to use a different style for the download page. I'll add a screenshot example.

I think you should be able to use the notice of hearing and motion (https://github.com/mplp/docassemble-Simpmotion) as an example for coding this. But let me know if you get stuck!
Variable being sought | `motion_re_change_of_domicile_download`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
here's an example of the download page

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/2bcd83f4-fd0a-4986-9a71-8d2334e6486f)

**Comment by h-mcguire** [comment]
I updated the download block in commit e624c70. But I couldn't get it to work how you'd like it. The documents are being listed out fully, and not being grouped into a the two viewable/downloadable format like the simple motion.  Here are screenshots of the code and the UI output. 

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/106545452/1e3c202a-59b0-4f8a-92db-9435fe5f6603)

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/106545452/97f70995-8e18-4626-86b5-52fa25997d78)

**Comment by ekressmiller** [comment]
Hi Hayden, I think you might have it!  The simple motion tool only produces one form, so only two docs are produced, the instructions and the form itself. Whereas here, since there are a few different forms, there will be more listed than that.
