### ISSUE TITLE
ID judgment or custody order: 
User feedback: bug
(`prior_order_yesno`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#6]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `judgment or custody order`
Details | got red error message when tried to answer no and continue
Variable being sought | `prior_order_yesno`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/72a3dd0f-38af-47c9-81a4-a0edd37359c3)
