### ISSUE TITLE
Table of Exhibits (wait to see if we're keeping this)

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#66]
If we keep the exhibit upload functionality, The top of the table of exhibits should probably have at least basic caption info added. At least the case number.

I think it's likely this table should come out as part of the Motion PDF as well, instead of as a separate PDF, but we would need to check with Amy on that.

**Comment by RamiLorca** [comment]
@ekressmiller, I realized I need some clarification on the type of basic caption info you had in mind. 

Right now the only pathway to upload documents is if the user indicates they're escaping domestic violence. Once this happens, the interview allows them to write an explanatory paragraph, followed by uploading documents. However, the user doesn't really have to indicate anything beyond that, such as a case number (see images below).

<img width="813" alt="Screenshot 2024-08-19 at 2 46 00 PM" src="https://github.com/user-attachments/assets/8f696e28-434f-48c1-bde9-3bd2e02043f9">

![Screenshot 2024-08-19 at 2 46 00 PM (2)](https://github.com/user-attachments/assets/639f013f-549f-42f0-b5da-7a346b0a3d02)

So with that being the case, do we want to collect additional info from the client? We could try adding optional fields for the client to provide more info about their potential DV case, but we may still end up with just the exhibit's letter and title in the Table of Exhibits.

**Comment by ekressmiller** [comment]
Hi Rami, no I wasn't imagining collecting anything extra. I meant something similar to what we have on the motion_re_cod_attachment doc:

![image](https://github.com/user-attachments/assets/bff6b69b-1fee-43eb-91ad-d5135a6e1dd6)
