### ISSUE TITLE
ID MLH_intro_landing: 
User feedback: something
(`MLH_intro_landing`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#7]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `MLH_intro_landing`
Details | I could be wrong, so ignore me if you have instructions to the contrary. But I think these may be specific to the child support tool.
Variable being sought | `MLH_intro_landing`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/d0e50cdc-c3de-4587-8a75-2123218b5f41)

**Comment by h-mcguire** [comment]
I don't believe we have instructions to the contrary. I double checked the LHI interview and it actually does not have a prompt like this, so we don't have situations to advise seeking counsel on. I updated the screen to the image below for now, but I assume some language could be added to inform litigants a bit more.

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/106545452/34bd795b-3e65-4364-8989-f86783fd23fb)
