### ISSUE TITLE
ID court_permission_required: 
User feedback: language
(`court_permission_required`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#8]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `court_permission_required`
Details | I like this, suggest using bolding (or possibly headers) to make it clearer
Variable being sought | `court_permission_required`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
Good idea how you reframed this!

Suggestion for words to bold:
<img width="338" alt="image" src="https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/314fc190-2ca7-4a7a-bbd1-d9d88ccc2678">
