### ISSUE TITLE
ID existing_case_kickout: 
User feedback: language
(`existing_case_kickout`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#9]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `existing_case_kickout`
Details | question refers to "child support case" but it should be more general "family law case"
Variable being sought | `existing_case_kickout`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/3fa1a571-c731-460d-bed2-363c7b05d132)
