### ISSUE TITLE
document uploader timeout

### ISSUE THREAD

**Issue by RamiLorca** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#99]
Document uploader tool occasionally times out when handling larger documents (around 11pages or so). Will need to replicate the issue and see if it can be fixed.

**Comment by ekressmiller** [comment]
Note: I think at least some of the timeouts I was seeing happened during the document assembly phase (at the end).

**Comment by ekressmiller** [comment]
Just did another test. I added the following documents:
Document 1 (1-page PDF 124 KB + 11-page PDF 2.92 MB)
Doc2 (1-page PDF 49.9 kb)

It took a while but uploaded the documents OK. At the download page, however, I got a nginx timeout error:
![image](https://github.com/user-attachments/assets/4d075563-e5f1-4052-b6b1-e024855346a6)

When I hit refresh, it did work.

**Comment by RamiLorca** [comment]
@ekressmiller I followed up with Quinten about this issue and it looks like we'll need to [increase the timeout to 5 minutes in the server](https://assemblyline.suffolklitlab.org/docs/get_started/installation/#increase-nginx-timeouts-to-5-minutes). Since it'll involve SSH'ing into the server, this may be something that'll require special permission.

**Comment by ekressmiller** [comment]
Timeout increased on dev and staging on 11/15 and on prod on 11/16
